### ISSUE TITLE
Error on enabling the plugin

### ISSUE THREAD

**Issue by Malauch** [dayjournal/qgis-attributeassignment-plugin#4]
When I tried to install and turn on the plugin I've got the error as below.

```
Nie można wczytać wtyczki 'AttributeAssignment' z powodu błędu wywołania jej metody classFactory() 

TypeError: 'QVariant' object is not subscriptable 
Traceback (most recent call last):
  File "/Applications/MacPorts/Qgis3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 337, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/michaljurewicz/Library/Application Support/QGIS/QGIS3/profiles/Profil2/python/plugins/AttributeAssignment/__init__.py", line 18, in classFactory
    return AttributeAssignment(iface)
  File "/Users/michaljurewicz/Library/Application Support/QGIS/QGIS3/profiles/Profil2/python/plugins/AttributeAssignment/AttributeAssignment.py", line 45, in __init__
    locale = QSettings().value('locale/userLocale')[0:2]
TypeError: 'QVariant' object is not subscriptable


Wersja Pythona: 3.6.6 (default, Jun 28 2018, 05:43:53) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] 
Wersja QGIS: 3.2.1-Bonn Bonn, exported 

Lokalizacja Pythona:
/Applications/MacPorts/Qgis3.app/Contents/MacOS/../Resources/python
/Users/michaljurewicz/Library/Application Support/QGIS/QGIS3/profiles/Profil2/python
/Users/michaljurewicz/Library/Application Support/QGIS/QGIS3/profiles/Profil2/python/plugins
/Applications/MacPorts/Qgis3.app/Contents/MacOS/../Resources/python/plugins
/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/michaljurewicz/Library/Application Support/QGIS/QGIS3/profiles/Profil2/python
/Users/michaljurewicz/Library/Application Support/QGIS/QGIS3/profiles/Profil2/python/plugins/mmqgis/forms
/Users/michaljurewicz/Library/Application Support/QGIS/QGIS3/profiles/Profil2/python/plugins/shapetools/ext-libs
```

**Comment by dayjournal** [comment]
I'm sorry.
It was not reproduced in my environment.

Windows 10 - QGIS 3.2.x
macOS High Sierra - QGIS 3.2.x

Would you delete the plugin and reinstall it?
